palette: Blues
dpi: 150
bands:
  ticket w/o AC:
    color: red
    range:
      - 0
      - 7
  readout delayed:
    color: orange
    range:
      - 7
      - 12
  solver GLPK failed:
    color: gray
    range:
      - 12
      - 18
  CI passed:
    color: lightgreen
    range:
      - 18
      - 26
  de-uro runs:
    color: darkgreen
    range:
      - 26
      - 35
  CT2 SUPERSTAR!:
    color: blue
    range:
      - 35
      - 70 # This should be the max possible score

# Mock scores to show on template chart. Reuses bands from above
mock_scores:
  player_1: 1
  player_2: 1
  player_3: 1
  player_4: 1
  player_5: 1
  player_6: 1
  player_7: 1



