
# read_from supports
# - `manual_csvs`: multiple csv files are expected from the different participants.
#      A csv with the correct answers must exist.
# - `google_forms`: all scores are expected to be contained in a single csv, exported
#     from Google forms. There is no need for a correct answers csv.
read_from: google_forms
name_col: Your first name # only relevant for google_forms input
palette: Blues
dpi: 150
bands:
  ticket w/o AC:
    color: red
    range:
      - 0
      - 15
  readout delayed:
    color: orange
    range:
      - 15
      - 21
  solver GLPK failed:
    color: gray
    range:
      - 21
      - 26
  CI passed:
    color: lightgreen
    range:
      - 26
      - 38
  de-uro runs:
    color: darkgreen
    range:
      - 38
      - 48
  CT2 SUPERSTAR!:
    color: blue
    range:
      - 48
      - 77 # This should be the max possible score

# Mock scores to show on template chart. Reuses bands from above
mock_scores:
  player_1: 1
  player_2: 1
  player_3: 1
  player_4: 1
  player_5: 1
  player_6: 1
  player_7: 1



